# Generated by Django 4.2.4 on 2023-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=100)),
                ("img_url", models.URLField()),
                ("description", models.TextField()),
                ("description_en", models.TextField()),
                ("anecdote", models.TextField()),
                ("rating_count", models.IntegerField()),
                ("rating_content", models.CharField(max_length=128)),
                ("year", models.CharField(max_length=128)),
                ("imdb_id", models.CharField(max_length=128)),
                ("actors", models.ManyToManyField(to="imdb.actor")),
            ],
        ),
    ]
