# Generated by Django 4.2.4 on 2023-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name="actor",
            name="name",
        ),
    ]
