# Generated by Django 4.2.4 on 2023-11-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0002_person_remove_actor_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AddField(
            model_name="actor",
            name="name",
            field=models.CharField(default="Null", max_length=128),
            preserve_default=False,
        ),
    ]
