# Generated by Django 4.2.7 on 2023-11-13 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0006_actorsmovies_directorsmovies_genre_genresmovies_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actor",
            table="actors",
        ),
        migrations.AlterModelTable(
            name="director",
            table="directors",
        ),
        migrations.AlterModelTable(
            name="movie",
            table="movies",
        ),
        migrations.AlterModelTable(
            name="scenarist",
            table="scenarists",
        ),
    ]
