# Generated by Django 4.2.7 on 2023-11-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("firstname", models.CharField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "actors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ActorsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "actors_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("firstname", models.CharField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "directors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DirectorsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "directors_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "genres",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GenresMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "genres_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id_movie", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(blank=True, max_length=256, null=True)),
                ("img_url", models.CharField(blank=True, max_length=256, null=True)),
                ("desc_fr", models.TextField(blank=True, null=True)),
                ("desc_en", models.TextField(blank=True, null=True)),
                ("anecdote", models.TextField(blank=True, null=True)),
                (
                    "rating_content",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("year", models.CharField(blank=True, max_length=256, null=True)),
                ("imdb_int", models.IntegerField(blank=True, null=True)),
                ("rating_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scenarist",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("firstname", models.CharField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "scenarists",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScenaristsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "scenarists_movies",
                "managed": False,
            },
        ),
    ]
