# Generated by Django 4.2.4 on 2023-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0004_director_movie_directors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenarist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="scenarists",
            field=models.ManyToManyField(to="imdb.scenarist"),
        ),
    ]
