# Generated by Django 4.2.4 on 2023-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb", "0005_scenarist_movie_scenarists"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "actors_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DirectorsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "directors_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "genres",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GenresMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "genres_movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScenaristsMovies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imdb_id", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "scenarists_movies",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="actor",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="scenarist",
            options={"managed": False},
        ),
    ]
